### ISSUE TITLE
crash get group id

### ISSUE THREAD

**Issue by envsh** [envsh/matterbridge#6]
```
runtime.cgocall(0xc43240, 0xc420815a68, 0x29)
        /usr/lib/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420815a28 sp=0xc4208159f0 pc=0x419584
github.com/TokTok/go-toxcore-c._Cfunc_tox_conference_get_identifier(0x29f3f00, 0xc400000000, 0xc42051dfb0, 0x0)
        _cgo_gotypes.go:1107 +0x4e fp=0xc420815a68 sp=0xc420815a28 pc=0xa203de
github.com/TokTok/go-toxcore-c.(*Tox).ConferenceGetIdentifier.func1(0x29f3f00, 0xc400000000, 0xc42051dfb0, 0xc42052a
888)
        /home/me/oss/src/github.com/TokTok/go-toxcore-c/group_intern.go:27 +0x97 fp=0xc420815aa0 sp=0xc420815a68
pc=0xa3c477
github.com/TokTok/go-toxcore-c.(*Tox).ConferenceGetIdentifier(0xc4204ae000, 0x0, 0x11584f0, 0xdbcd20, 0xc42080c300,
0x429c01)
        /home/me/oss/src/github.com/TokTok/go-toxcore-c/group_intern.go:27 +0x5a fp=0xc420815ae0 sp=0xc420815aa0
pc=0xa2fb3a
github.com/envsh/go-toxcore/xtox.(*_XTox).initHooks.func3(0xc400000000)
        /home/me/oss/src/github.com/envsh/go-toxcore/xtox/xtox.go:302 +0x34e fp=0xc420815c30 sp=0xc420815ae0 pc=0
xa4b28e
```

```
#0  get_group_c (groupnumber=0, tox=0x7fffc8000b70) at group_intern.c:240
#1  tox_conference_get_identifier (tox=0x7fffc8000b70, conference_number=0, idbuf=0xc42052d710)
    at group_intern.c:248
#2  0x0000000000c4325e in _cgo_754818c775db_Cfunc_tox_conference_get_identifier (v=0xc42048fa68)
    at cgo-gcc-prolog:43
#3  0x0000000000470d50 in runtime.asmcgocall () at /usr/lib/go/src/runtime/asm_amd64.s:688
#4  0x0000000000000000 in ?? ()
```

**Comment by envsh** [comment]
fixed by https://github.com/envsh/go-toxcore-c/commit/9786e0a4da43f1751d9ea61663f65e161e1e1c24
